// 수능 필수 어휘 500개 — 수능 빈출 추상명사, 학술동사, 다의어, 형용사/부사, 연결어 중심
const VOCAB_DB = [
  // ══════════════════════════════════════
  // 추상 명사 (80개)
  // ══════════════════════════════════════
  {word:"implication",meaning:"함축, 영향",example:"The implications of this research are far-reaching.",category:"추상명사"},
  {word:"autonomy",meaning:"자율성",example:"Students need more autonomy in their learning.",category:"추상명사"},
  {word:"consistency",meaning:"일관성",example:"Consistency is key to building good habits.",category:"추상명사"},
  {word:"perception",meaning:"인식, 지각",example:"Our perception of reality is shaped by experience.",category:"추상명사"},
  {word:"perspective",meaning:"관점, 시각",example:"Try to see things from a different perspective.",category:"추상명사"},
  {word:"phenomenon",meaning:"현상",example:"This phenomenon can be explained by social psychology.",category:"추상명사"},
  {word:"constraint",meaning:"제약, 제한",example:"Budget constraints limit what we can achieve.",category:"추상명사"},
  {word:"incentive",meaning:"동기, 유인",example:"Financial incentives can motivate employees.",category:"추상명사"},
  {word:"paradox",meaning:"역설, 모순",example:"It is a paradox that too much choice can reduce satisfaction.",category:"추상명사"},
  {word:"hypothesis",meaning:"가설",example:"The hypothesis was supported by the experimental data.",category:"추상명사"},
  {word:"analogy",meaning:"유추, 비유",example:"He drew an analogy between the brain and a computer.",category:"추상명사"},
  {word:"ambiguity",meaning:"모호성, 애매함",example:"The ambiguity of the statement led to confusion.",category:"추상명사"},
  {word:"bias",meaning:"편견, 편향",example:"Confirmation bias affects how we interpret information.",category:"추상명사"},
  {word:"consensus",meaning:"합의, 의견 일치",example:"There is a growing consensus among scientists.",category:"추상명사"},
  {word:"criterion",meaning:"기준 (복수: criteria)",example:"What criteria did you use to evaluate the proposals?",category:"추상명사"},
  {word:"dilemma",meaning:"딜레마, 진퇴양난",example:"She faced a dilemma between career and family.",category:"추상명사"},
  {word:"empathy",meaning:"공감, 감정이입",example:"Empathy allows us to understand others' feelings.",category:"추상명사"},
  {word:"hierarchy",meaning:"위계, 계층",example:"The company has a strict hierarchy.",category:"추상명사"},
  {word:"infrastructure",meaning:"기반 시설",example:"Investing in infrastructure is essential for growth.",category:"추상명사"},
  {word:"norm",meaning:"규범, 기준",example:"Social norms vary across cultures.",category:"추상명사"},
  {word:"stimulus",meaning:"자극",example:"The stimulus triggered a rapid response.",category:"추상명사"},
  {word:"commodity",meaning:"상품, 일용품",example:"Oil is a globally traded commodity.",category:"추상명사"},
  {word:"rhetoric",meaning:"수사학, 미사여구",example:"Political rhetoric can be misleading.",category:"추상명사"},
  {word:"paradigm",meaning:"패러다임, 전형",example:"A paradigm shift occurred in scientific thinking.",category:"추상명사"},
  {word:"disparity",meaning:"불균형, 차이",example:"Income disparity has been growing rapidly.",category:"추상명사"},
  {word:"prosperity",meaning:"번영, 번성",example:"Economic prosperity depends on education.",category:"추상명사"},
  {word:"equilibrium",meaning:"균형, 평형",example:"The ecosystem maintains a delicate equilibrium.",category:"추상명사"},
  {word:"trajectory",meaning:"궤도, 궤적",example:"The trajectory of her career was impressive.",category:"추상명사"},
  {word:"discourse",meaning:"담론, 담화",example:"Public discourse on climate change has intensified.",category:"추상명사"},
  {word:"prevalence",meaning:"유행, 보급",example:"The prevalence of diabetes is increasing.",category:"추상명사"},
  {word:"coherence",meaning:"일관성, 응집력",example:"The essay lacks coherence in its arguments.",category:"추상명사"},
  {word:"inclination",meaning:"경향, 성향",example:"He has an inclination toward the arts.",category:"추상명사"},
  {word:"rationale",meaning:"근거, 이유",example:"What is the rationale behind this decision?",category:"추상명사"},
  {word:"threshold",meaning:"문턱, 한계점",example:"The noise exceeded the acceptable threshold.",category:"추상명사"},
  {word:"surplus",meaning:"잉여, 과잉",example:"The country has a trade surplus.",category:"추상명사"},
  {word:"deficit",meaning:"부족, 적자",example:"The budget deficit continues to grow.",category:"추상명사"},
  {word:"monopoly",meaning:"독점",example:"The company held a monopoly on the market.",category:"추상명사"},
  {word:"bureaucracy",meaning:"관료제, 관료주의",example:"Bureaucracy often slows down decision-making.",category:"추상명사"},
  {word:"autonomy",meaning:"자율, 자치",example:"The region gained political autonomy.",category:"추상명사"},
  {word:"adversity",meaning:"역경, 어려움",example:"She showed great courage in the face of adversity.",category:"추상명사"},
  {word:"integrity",meaning:"진실성, 완전함",example:"He is known for his integrity and honesty.",category:"추상명사"},
  {word:"prestige",meaning:"명성, 위신",example:"The university enjoys international prestige.",category:"추상명사"},
  {word:"scrutiny",meaning:"정밀 조사, 면밀한 검토",example:"The proposal came under close scrutiny.",category:"추상명사"},
  {word:"susceptibility",meaning:"민감성, 취약성",example:"Children have a higher susceptibility to infections.",category:"추상명사"},
  {word:"hegemony",meaning:"패권, 지배력",example:"Cultural hegemony shapes public opinion.",category:"추상명사"},
  {word:"jurisdiction",meaning:"관할권, 사법권",example:"This matter falls outside our jurisdiction.",category:"추상명사"},
  {word:"reciprocity",meaning:"상호성, 호혜",example:"Reciprocity is the basis of healthy relationships.",category:"추상명사"},
  {word:"stigma",meaning:"낙인, 오명",example:"There is a stigma attached to mental illness.",category:"추상명사"},
  {word:"allegiance",meaning:"충성, 충의",example:"Citizens pledge allegiance to their country.",category:"추상명사"},
  {word:"nuance",meaning:"뉘앙스, 미묘한 차이",example:"The nuances of the language are hard to master.",category:"추상명사"},
  {word:"facet",meaning:"측면, 양상",example:"There are many facets to this problem.",category:"추상명사"},
  {word:"plurality",meaning:"다수, 복수",example:"A plurality of opinions enriches the debate.",category:"추상명사"},
  {word:"predicament",meaning:"곤경, 궁지",example:"He found himself in a difficult predicament.",category:"추상명사"},
  {word:"proximity",meaning:"근접, 가까움",example:"The proximity of the school was a deciding factor.",category:"추상명사"},
  {word:"realm",meaning:"영역, 분야",example:"This falls within the realm of philosophy.",category:"추상명사"},
  {word:"sentiment",meaning:"감정, 정서",example:"Public sentiment turned against the policy.",category:"추상명사"},
  {word:"solidarity",meaning:"연대, 결속",example:"The workers showed solidarity during the strike.",category:"추상명사"},
  {word:"sovereignty",meaning:"주권, 통치권",example:"National sovereignty must be respected.",category:"추상명사"},
  {word:"synthesis",meaning:"종합, 합성",example:"The report is a synthesis of multiple studies.",category:"추상명사"},
  {word:"turbulence",meaning:"난기류, 혼란",example:"The economy experienced a period of turbulence.",category:"추상명사"},
  {word:"vulnerability",meaning:"취약성, 약점",example:"Climate change increases our vulnerability to disasters.",category:"추상명사"},
  {word:"aftermath",meaning:"여파, 결과",example:"In the aftermath of the war, rebuilding began.",category:"추상명사"},
  {word:"analogy",meaning:"유추, 유사점",example:"There is an analogy between the heart and a pump.",category:"추상명사"},
  {word:"apparatus",meaning:"기구, 장치",example:"The scientific apparatus was expensive.",category:"추상명사"},
  {word:"apathy",meaning:"무관심, 냉담",example:"Voter apathy is a threat to democracy.",category:"추상명사"},
  {word:"aspiration",meaning:"열망, 포부",example:"She had aspirations of becoming a doctor.",category:"추상명사"},
  {word:"austerity",meaning:"긴축, 검소",example:"The government imposed austerity measures.",category:"추상명사"},
  {word:"benevolence",meaning:"자비, 선행",example:"His benevolence was known throughout the community.",category:"추상명사"},
  {word:"complacency",meaning:"안주, 현실 안주",example:"Success can breed complacency.",category:"추상명사"},
  {word:"contingency",meaning:"우발 사태, 비상 사태",example:"We need a contingency plan.",category:"추상명사"},
  {word:"contention",meaning:"논쟁, 다툼",example:"The main point of contention was funding.",category:"추상명사"},
  {word:"deprivation",meaning:"박탈, 결핍",example:"Sleep deprivation affects cognitive performance.",category:"추상명사"},
  {word:"deterrent",meaning:"억제력, 방해물",example:"Nuclear weapons serve as a deterrent.",category:"추상명사"},
  {word:"endeavor",meaning:"노력, 시도",example:"Scientific endeavor requires patience.",category:"추상명사"},
  {word:"entropy",meaning:"무질서, 엔트로피",example:"Entropy in a closed system always increases.",category:"추상명사"},
  {word:"fallacy",meaning:"오류, 궤변",example:"The argument contains a logical fallacy.",category:"추상명사"},
  {word:"grievance",meaning:"불만, 고충",example:"Workers filed a grievance against management.",category:"추상명사"},
  {word:"heyday",meaning:"전성기, 절정기",example:"The 1960s were the heyday of rock music.",category:"추상명사"},
  {word:"hindsight",meaning:"뒤늦은 깨달음",example:"In hindsight, the decision was wrong.",category:"추상명사"},
  {word:"impetus",meaning:"자극, 추진력",example:"The crisis gave impetus to reform.",category:"추상명사"},

  // ══════════════════════════════════════
  // 학술 동사 (100개)
  // ══════════════════════════════════════
  {word:"constitute",meaning:"구성하다, ~이 되다",example:"Women constitute 60% of the workforce.",category:"학술동사"},
  {word:"undermine",meaning:"약화시키다, 손상시키다",example:"Lack of sleep undermines cognitive performance.",category:"학술동사"},
  {word:"facilitate",meaning:"촉진하다, 용이하게 하다",example:"Technology facilitates communication across borders.",category:"학술동사"},
  {word:"perceive",meaning:"인식하다, 감지하다",example:"Children perceive the world differently from adults.",category:"학술동사"},
  {word:"attribute",meaning:"~의 탓으로 돌리다",example:"She attributed her success to hard work.",category:"학술동사"},
  {word:"reinforce",meaning:"강화하다, 보강하다",example:"Positive feedback reinforces desired behavior.",category:"학술동사"},
  {word:"conform",meaning:"따르다, 순응하다",example:"People tend to conform to group expectations.",category:"학술동사"},
  {word:"enhance",meaning:"향상시키다",example:"Exercise enhances both physical and mental health.",category:"학술동사"},
  {word:"distort",meaning:"왜곡하다",example:"Memories can be distorted over time.",category:"학술동사"},
  {word:"cultivate",meaning:"기르다, 경작하다",example:"Schools should cultivate critical thinking skills.",category:"학술동사"},
  {word:"diminish",meaning:"줄이다, 감소시키다",example:"Nothing can diminish the importance of education.",category:"학술동사"},
  {word:"elaborate",meaning:"정교하게 만들다, 상세히 설명하다",example:"Could you elaborate on your point?",category:"학술동사"},
  {word:"encompass",meaning:"포함하다, 포괄하다",example:"The study encompasses a wide range of topics.",category:"학술동사"},
  {word:"exploit",meaning:"이용하다, 착취하다",example:"Companies exploit consumer psychology to increase sales.",category:"학술동사"},
  {word:"incorporate",meaning:"통합하다, 포함시키다",example:"The new design incorporates user feedback.",category:"학술동사"},
  {word:"inhibit",meaning:"억제하다, 방해하다",example:"Fear can inhibit creative thinking.",category:"학술동사"},
  {word:"manifest",meaning:"나타내다, 드러내다",example:"Stress can manifest itself in physical symptoms.",category:"학술동사"},
  {word:"overlook",meaning:"간과하다, 못 보고 지나치다",example:"We should not overlook the importance of sleep.",category:"학술동사"},
  {word:"precede",meaning:"선행하다, 앞서다",example:"A brief introduction preceded the main lecture.",category:"학술동사"},
  {word:"sustain",meaning:"유지하다, 지탱하다",example:"It is difficult to sustain motivation over time.",category:"학술동사"},
  {word:"aggregate",meaning:"모으다, 합산하다",example:"We aggregated data from multiple sources.",category:"학술동사"},
  {word:"alleviate",meaning:"완화하다, 경감하다",example:"Medication can alleviate the symptoms.",category:"학술동사"},
  {word:"anticipate",meaning:"예상하다, 기대하다",example:"We did not anticipate such strong opposition.",category:"학술동사"},
  {word:"articulate",meaning:"분명히 표현하다",example:"She articulated her ideas clearly.",category:"학술동사"},
  {word:"assert",meaning:"주장하다, 단언하다",example:"He asserted that the theory was correct.",category:"학술동사"},
  {word:"assimilate",meaning:"동화시키다, 흡수하다",example:"Immigrants gradually assimilate into the culture.",category:"학술동사"},
  {word:"coincide",meaning:"동시에 발생하다, 일치하다",example:"The two events coincided perfectly.",category:"학술동사"},
  {word:"compensate",meaning:"보상하다, 보충하다",example:"Higher pay compensates for the longer hours.",category:"학술동사"},
  {word:"complement",meaning:"보완하다",example:"The two systems complement each other well.",category:"학술동사"},
  {word:"compel",meaning:"강요하다, ~하지 않을 수 없게 하다",example:"The evidence compelled him to change his mind.",category:"학술동사"},
  {word:"conceive",meaning:"생각해내다, 임신하다",example:"It is hard to conceive of a world without technology.",category:"학술동사"},
  {word:"confine",meaning:"한정하다, 가두다",example:"The discussion was confined to economic issues.",category:"학술동사"},
  {word:"contradict",meaning:"모순되다, 반박하다",example:"The results contradict the original hypothesis.",category:"학술동사"},
  {word:"converge",meaning:"수렴하다, 모이다",example:"Several factors converged to cause the crisis.",category:"학술동사"},
  {word:"correlate",meaning:"상관관계가 있다",example:"Income levels correlate with education levels.",category:"학술동사"},
  {word:"deduce",meaning:"추론하다, 연역하다",example:"From the evidence, we can deduce the cause.",category:"학술동사"},
  {word:"depict",meaning:"묘사하다, 그리다",example:"The painting depicts a rural landscape.",category:"학술동사"},
  {word:"derive",meaning:"유래하다, 얻다",example:"The word derives from Latin.",category:"학술동사"},
  {word:"designate",meaning:"지정하다, 지명하다",example:"The area was designated as a national park.",category:"학술동사"},
  {word:"deviate",meaning:"벗어나다, 일탈하다",example:"The results deviate from the expected pattern.",category:"학술동사"},
  {word:"displace",meaning:"대체하다, 쫓아내다",example:"Machines have displaced many manual workers.",category:"학술동사"},
  {word:"elicit",meaning:"이끌어내다, 유발하다",example:"The question elicited a surprising response.",category:"학술동사"},
  {word:"embody",meaning:"구현하다, 구체화하다",example:"She embodies the spirit of the organization.",category:"학술동사"},
  {word:"endorse",meaning:"지지하다, 보증하다",example:"The committee endorsed the proposal.",category:"학술동사"},
  {word:"entail",meaning:"수반하다, 필요로 하다",example:"The project entails significant investment.",category:"학술동사"},
  {word:"evoke",meaning:"불러일으키다, 환기시키다",example:"The music evoked memories of childhood.",category:"학술동사"},
  {word:"exert",meaning:"(힘·영향을) 행사하다",example:"Parents exert a strong influence on children.",category:"학술동사"},
  {word:"formulate",meaning:"공식화하다, 고안하다",example:"Scientists formulated a new theory.",category:"학술동사"},
  {word:"hinder",meaning:"방해하다, 저해하다",example:"Bad weather hindered the rescue operation.",category:"학술동사"},
  {word:"impose",meaning:"부과하다, 강요하다",example:"The government imposed new regulations.",category:"학술동사"},
  {word:"induce",meaning:"유도하다, 유발하다",example:"Stress can induce health problems.",category:"학술동사"},
  {word:"infer",meaning:"추론하다",example:"We can infer the meaning from context.",category:"학술동사"},
  {word:"instigate",meaning:"선동하다, 유발하다",example:"He instigated a change in company policy.",category:"학술동사"},
  {word:"integrate",meaning:"통합하다",example:"The school integrated technology into the curriculum.",category:"학술동사"},
  {word:"intervene",meaning:"개입하다, 중재하다",example:"The government intervened to stabilize the economy.",category:"학술동사"},
  {word:"invoke",meaning:"발동하다, 언급하다",example:"She invoked the principles of justice.",category:"학술동사"},
  {word:"legitimate",meaning:"합법화하다, 정당화하다",example:"The election legitimated the new government.",category:"학술동사"},
  {word:"mediate",meaning:"중재하다, 매개하다",example:"She mediated the dispute between the two parties.",category:"학술동사"},
  {word:"mitigate",meaning:"완화하다, 경감하다",example:"Steps were taken to mitigate the damage.",category:"학술동사"},
  {word:"modify",meaning:"수정하다, 변경하다",example:"We need to modify the original plan.",category:"학술동사"},
  {word:"negate",meaning:"부정하다, 무효화하다",example:"One mistake can negate all your efforts.",category:"학술동사"},
  {word:"obscure",meaning:"모호하게 하다, 가리다",example:"The fog obscured the view of the mountain.",category:"학술동사"},
  {word:"offset",meaning:"상쇄하다, 벌충하다",example:"The gains offset the earlier losses.",category:"학술동사"},
  {word:"perpetuate",meaning:"영속시키다, 지속시키다",example:"Stereotypes perpetuate inequality.",category:"학술동사"},
  {word:"postulate",meaning:"가정하다, 상정하다",example:"The scientist postulated a new theory.",category:"학술동사"},
  {word:"prescribe",meaning:"처방하다, 규정하다",example:"The law prescribes strict penalties.",category:"학술동사"},
  {word:"presume",meaning:"추정하다, 가정하다",example:"I presume you have read the report.",category:"학술동사"},
  {word:"prevail",meaning:"만연하다, 우세하다",example:"Justice will prevail in the end.",category:"학술동사"},
  {word:"propagate",meaning:"전파하다, 번식시키다",example:"Social media propagates information rapidly.",category:"학술동사"},
  {word:"reconcile",meaning:"화해시키다, 조화시키다",example:"It is hard to reconcile these two views.",category:"학술동사"},
  {word:"replicate",meaning:"복제하다, 재현하다",example:"The experiment was replicated with the same results.",category:"학술동사"},
  {word:"restore",meaning:"복원하다, 회복시키다",example:"Efforts to restore the damaged ecosystem succeeded.",category:"학술동사"},
  {word:"retain",meaning:"유지하다, 보유하다",example:"The company retained its market share.",category:"학술동사"},
  {word:"scrutinize",meaning:"면밀히 조사하다",example:"The data was carefully scrutinized.",category:"학술동사"},
  {word:"simulate",meaning:"모의실험하다, 흉내내다",example:"The software simulates real-world conditions.",category:"학술동사"},
  {word:"speculate",meaning:"추측하다, 투기하다",example:"Scientists speculate about the origin of life.",category:"학술동사"},
  {word:"stipulate",meaning:"규정하다, 명시하다",example:"The contract stipulates a deadline.",category:"학술동사"},
  {word:"subordinate",meaning:"종속시키다, 하위에 두다",example:"He subordinated his interests to the group.",category:"학술동사"},
  {word:"supersede",meaning:"대체하다, 대신하다",example:"New technology superseded the old system.",category:"학술동사"},
  {word:"supplement",meaning:"보충하다",example:"He supplemented his income with freelance work.",category:"학술동사"},
  {word:"transcend",meaning:"초월하다",example:"Great art transcends cultural boundaries.",category:"학술동사"},

  // ══════════════════════════════════════
  // 다의어 — 수능 빈출 뜻 (60개)
  // ══════════════════════════════════════
  {word:"address",meaning:"다루다, 해결하다 (주소 외)",example:"We need to address the issue of inequality.",category:"다의어"},
  {word:"account",meaning:"설명, 차지하다 (계좌 외)",example:"Exports account for 40% of the economy.",category:"다의어"},
  {word:"run",meaning:"운영하다, 진행되다 (달리다 외)",example:"She runs a successful business.",category:"다의어"},
  {word:"issue",meaning:"쟁점, 발행하다 (문제 외)",example:"Climate change is a pressing issue.",category:"다의어"},
  {word:"figure",meaning:"인물, 수치, 이해하다",example:"She is an important figure in modern art.",category:"다의어"},
  {word:"character",meaning:"성격, 특성 (인물/문자 외)",example:"The character of the neighborhood has changed.",category:"다의어"},
  {word:"engage",meaning:"관여시키다, 참여하다",example:"The teacher tried to engage students in discussion.",category:"다의어"},
  {word:"interest",meaning:"이해관계, 이자 (관심 외)",example:"He has a financial interest in the company.",category:"다의어"},
  {word:"matter",meaning:"중요하다, 물질 (문제 외)",example:"What matters most is your effort.",category:"다의어"},
  {word:"practice",meaning:"관행, 실천 (연습 외)",example:"This practice has been common for centuries.",category:"다의어"},
  {word:"produce",meaning:"농산물, 야기하다 (생산하다 외)",example:"Fresh produce is available at the market.",category:"다의어"},
  {word:"subject",meaning:"대상, 지배하에 있는 (과목 외)",example:"All citizens are subject to the law.",category:"다의어"},
  {word:"term",meaning:"용어, 관점에서 (기간 외)",example:"In economic terms, this policy makes sense.",category:"다의어"},
  {word:"yield",meaning:"산출하다, 양보하다 (수확량 외)",example:"The experiment yielded unexpected results.",category:"다의어"},
  {word:"channel",meaning:"경로, 전달하다 (채널 외)",example:"She channeled her anger into creative work.",category:"다의어"},
  {word:"craft",meaning:"기술, 정성들여 만들다 (공예 외)",example:"He carefully crafted his argument.",category:"다의어"},
  {word:"discipline",meaning:"훈련, 학문 분야 (규율 외)",example:"Sociology is a discipline within social science.",category:"다의어"},
  {word:"exercise",meaning:"행사하다, 발휘하다 (운동 외)",example:"Citizens should exercise their right to vote.",category:"다의어"},
  {word:"fashion",meaning:"방식, 만들어내다 (패션 외)",example:"He answered in a calm fashion.",category:"다의어"},
  {word:"ground",meaning:"근거, 기초 (땅 외)",example:"On what grounds do you make that claim?",category:"다의어"},
  {word:"measure",meaning:"조치, 척도 (측정하다 외)",example:"The government took measures to reduce pollution.",category:"다의어"},
  {word:"minute",meaning:"미세한, 극히 작은 (분 외)",example:"Scientists detected minute changes in temperature.",category:"다의어"},
  {word:"note",meaning:"주목하다, 언급하다 (노트 외)",example:"It is worth noting that the data is limited.",category:"다의어"},
  {word:"object",meaning:"반대하다 (물체/목적 외)",example:"Several members objected to the proposal.",category:"다의어"},
  {word:"order",meaning:"질서, 명령하다 (순서 외)",example:"The police were called to restore order.",category:"다의어"},
  {word:"pool",meaning:"공동출자하다, 모으다 (수영장 외)",example:"They pooled their resources to start a business.",category:"다의어"},
  {word:"present",meaning:"제시하다, 현재의 (선물 외)",example:"She presented her findings at the conference.",category:"다의어"},
  {word:"project",meaning:"투사하다, 예상하다 (프로젝트 외)",example:"Experts project a rise in temperatures.",category:"다의어"},
  {word:"relief",meaning:"안도, 완화 (구호 외)",example:"The medicine brought relief from the pain.",category:"다의어"},
  {word:"resort",meaning:"의지하다 (리조트 외)",example:"We had to resort to extreme measures.",category:"다의어"},
  {word:"rest",meaning:"나머지 (쉬다 외)",example:"The rest of the students stayed behind.",category:"다의어"},
  {word:"scale",meaning:"규모, 비율 (저울 외)",example:"The scale of the disaster was enormous.",category:"다의어"},
  {word:"school",meaning:"학파 (학교 외)",example:"He belongs to the Chicago school of economics.",category:"다의어"},
  {word:"settle",meaning:"정착하다, 해결하다 (앉다 외)",example:"They settled the dispute out of court.",category:"다의어"},
  {word:"sound",meaning:"건전한, 타당한 (소리 외)",example:"His advice was sound and practical.",category:"다의어"},
  {word:"spell",meaning:"의미하다, 초래하다 (철자 외)",example:"This could spell disaster for the economy.",category:"다의어"},
  {word:"spring",meaning:"생겨나다, 비롯되다 (봄 외)",example:"Her creativity springs from personal experience.",category:"다의어"},
  {word:"stand",meaning:"입장, 견디다 (서다 외)",example:"What is your stand on this issue?",category:"다의어"},
  {word:"state",meaning:"진술하다, 상태 (국가 외)",example:"He clearly stated his position.",category:"다의어"},
  {word:"store",meaning:"비축, 저장하다 (가게 외)",example:"The brain stores vast amounts of information.",category:"다의어"},
  {word:"stock",meaning:"재고, 비축하다 (주식 외)",example:"The store stocked a wide variety of goods.",category:"다의어"},
  {word:"strain",meaning:"부담, 긴장 (품종 외)",example:"The crisis put a strain on the economy.",category:"다의어"},
  {word:"tap",meaning:"활용하다 (두드리다 외)",example:"We need to tap into renewable energy sources.",category:"다의어"},
  {word:"volume",meaning:"양, 부피 (책/음량 외)",example:"The volume of trade has increased significantly.",category:"다의어"},
  {word:"weather",meaning:"이겨내다 (날씨 외)",example:"The company weathered the economic storm.",category:"다의어"},
  {word:"work",meaning:"작용하다, 효과가 있다 (일 외)",example:"The medicine works within an hour.",category:"다의어"},
  {word:"bear",meaning:"견디다, 낳다 (곰 외)",example:"She could not bear the thought of losing him.",category:"다의어"},
  {word:"command",meaning:"구사하다, 통솔하다 (명령 외)",example:"She commands three languages fluently.",category:"다의어"},
  {word:"commit",meaning:"전념하다, 범하다 (약속하다 외)",example:"He committed himself to the cause.",category:"다의어"},
  {word:"contain",meaning:"억누르다, 포함하다",example:"She struggled to contain her anger.",category:"다의어"},
  {word:"cover",meaning:"다루다, 충당하다 (덮다 외)",example:"The article covers a wide range of topics.",category:"다의어"},
  {word:"drive",meaning:"추진력, 몰아가다 (운전 외)",example:"Curiosity drives scientific discovery.",category:"다의어"},
  {word:"float",meaning:"떠다니다, 제안하다 (뜨다 외)",example:"She floated the idea at the meeting.",category:"다의어"},
  {word:"given",meaning:"~을 고려하면 (주어진 외)",example:"Given the circumstances, he did well.",category:"다의어"},
  {word:"hold",meaning:"유효하다, 적용되다 (잡다 외)",example:"This rule holds true in most cases.",category:"다의어"},
  {word:"lean",meaning:"의존하다, 기울다 (마른 외)",example:"He leaned on his friends for support.",category:"다의어"},
  {word:"leave",meaning:"맡기다, 남기다 (떠나다 외)",example:"I leave the decision to you.",category:"다의어"},
  {word:"mean",meaning:"비열한, 의미하다 (뜻하다 외)",example:"Success means different things to different people.",category:"다의어"},
  {word:"nature",meaning:"본질, 특성 (자연 외)",example:"The nature of the problem is complex.",category:"다의어"},
  {word:"passage",meaning:"통과, 추이 (통로 외)",example:"The passage of time heals wounds.",category:"다의어"},

  // ══════════════════════════════════════
  // 반의어 쌍 (30개)
  // ══════════════════════════════════════
  {word:"enhance",meaning:"향상시키다 ↔ diminish",example:"Good design enhances the user experience.",category:"반의어쌍"},
  {word:"facilitate",meaning:"촉진하다 ↔ hinder",example:"Clear instructions facilitate understanding.",category:"반의어쌍"},
  {word:"reinforce",meaning:"강화하다 ↔ undermine",example:"Evidence reinforces the theory.",category:"반의어쌍"},
  {word:"embrace",meaning:"받아들이다 ↔ reject",example:"We should embrace change rather than fear it.",category:"반의어쌍"},
  {word:"foster",meaning:"촉진하다, 기르다 ↔ suppress",example:"A supportive environment fosters creativity.",category:"반의어쌍"},
  {word:"amplify",meaning:"증폭하다 ↔ reduce",example:"Social media can amplify misinformation.",category:"반의어쌍"},
  {word:"accelerate",meaning:"가속하다 ↔ decelerate",example:"Technology accelerates the pace of change.",category:"반의어쌍"},
  {word:"acknowledge",meaning:"인정하다 ↔ deny",example:"He acknowledged his mistake.",category:"반의어쌍"},
  {word:"disclose",meaning:"공개하다 ↔ conceal",example:"The company refused to disclose the information.",category:"반의어쌍"},
  {word:"elaborate",meaning:"정교한 ↔ simple",example:"The plan was too elaborate to execute.",category:"반의어쌍"},
  {word:"accumulate",meaning:"축적하다 ↔ deplete",example:"Wealth accumulates over generations.",category:"반의어쌍"},
  {word:"rigid",meaning:"경직된 ↔ flexible",example:"The rules are too rigid to allow creativity.",category:"반의어쌍"},
  {word:"abstract",meaning:"추상적인 ↔ concrete",example:"The concept remains too abstract.",category:"반의어쌍"},
  {word:"voluntary",meaning:"자발적인 ↔ compulsory",example:"Participation is voluntary.",category:"반의어쌍"},
  {word:"innate",meaning:"타고난 ↔ acquired",example:"Is language ability innate or acquired?",category:"반의어쌍"},
  {word:"explicit",meaning:"명시적인 ↔ implicit",example:"The instructions were explicit and clear.",category:"반의어쌍"},
  {word:"homogeneous",meaning:"동질적인 ↔ heterogeneous",example:"The population is becoming less homogeneous.",category:"반의어쌍"},
  {word:"objective",meaning:"객관적인 ↔ subjective",example:"We need an objective analysis of the data.",category:"반의어쌍"},
  {word:"surplus",meaning:"과잉 ↔ deficit",example:"The country recorded a budget surplus.",category:"반의어쌍"},
  {word:"converge",meaning:"수렴하다 ↔ diverge",example:"The two roads converge at the bridge.",category:"반의어쌍"},
  {word:"peripheral",meaning:"주변적인 ↔ central",example:"This is a peripheral issue, not the main one.",category:"반의어쌍"},
  {word:"superficial",meaning:"표면적인 ↔ profound",example:"His analysis was superficial at best.",category:"반의어쌍"},
  {word:"transient",meaning:"일시적인 ↔ permanent",example:"The effects were transient.",category:"반의어쌍"},
  {word:"preceding",meaning:"이전의 ↔ subsequent",example:"The preceding chapter explains the theory.",category:"반의어쌍"},
  {word:"scarce",meaning:"부족한 ↔ abundant",example:"Clean water is scarce in many regions.",category:"반의어쌍"},
  {word:"prohibit",meaning:"금지하다 ↔ permit",example:"Smoking is prohibited in public areas.",category:"반의어쌍"},
  {word:"thrive",meaning:"번성하다 ↔ decline",example:"Plants thrive in sunlight.",category:"반의어쌍"},
  {word:"ascend",meaning:"올라가다 ↔ descend",example:"The balloon ascended into the sky.",category:"반의어쌍"},
  {word:"exempt",meaning:"면제된 ↔ liable",example:"Students are exempt from the tax.",category:"반의어쌍"},
  {word:"dormant",meaning:"휴면 중인 ↔ active",example:"The volcano has been dormant for centuries.",category:"반의어쌍"},

  // ══════════════════════════════════════
  // 형용사 (100개)
  // ══════════════════════════════════════
  {word:"inherent",meaning:"본래 갖추어진, 내재하는",example:"There are inherent risks in any investment.",category:"형용사"},
  {word:"unprecedented",meaning:"전례 없는",example:"The pandemic caused an unprecedented crisis.",category:"형용사"},
  {word:"prevalent",meaning:"널리 퍼진, 유행하는",example:"Obesity is becoming increasingly prevalent.",category:"형용사"},
  {word:"deliberate",meaning:"의도적인, 신중한",example:"It was a deliberate attempt to mislead.",category:"형용사"},
  {word:"subtle",meaning:"미묘한, 감지하기 어려운",example:"There is a subtle difference between the two.",category:"형용사"},
  {word:"profound",meaning:"심오한, 깊은",example:"The discovery had a profound impact on science.",category:"형용사"},
  {word:"rigid",meaning:"엄격한, 경직된",example:"Rigid rules can stifle innovation.",category:"형용사"},
  {word:"superficial",meaning:"피상적인, 표면적인",example:"His understanding of the topic was superficial.",category:"형용사"},
  {word:"compatible",meaning:"양립 가능한, 호환되는",example:"The new system is compatible with older devices.",category:"형용사"},
  {word:"compelling",meaning:"설득력 있는, 강렬한",example:"She made a compelling argument for change.",category:"형용사"},
  {word:"inevitable",meaning:"불가피한, 피할 수 없는",example:"Change is inevitable in a growing organization.",category:"형용사"},
  {word:"plausible",meaning:"그럴듯한, 타당한",example:"His explanation was plausible but unproven.",category:"형용사"},
  {word:"tangible",meaning:"실체가 있는, 만질 수 있는",example:"We need tangible evidence to support the claim.",category:"형용사"},
  {word:"feasible",meaning:"실행 가능한",example:"The plan is technically feasible.",category:"형용사"},
  {word:"legitimate",meaning:"합법적인, 정당한",example:"He raised a legitimate concern.",category:"형용사"},
  {word:"detrimental",meaning:"해로운, 유해한",example:"Smoking is detrimental to health.",category:"형용사"},
  {word:"ambiguous",meaning:"모호한, 애매한",example:"The wording of the law is ambiguous.",category:"형용사"},
  {word:"arbitrary",meaning:"임의의, 자의적인",example:"The decision seemed arbitrary and unfair.",category:"형용사"},
  {word:"chronic",meaning:"만성적인, 고질적인",example:"Chronic stress can lead to health problems.",category:"형용사"},
  {word:"cognitive",meaning:"인지의, 인식의",example:"Cognitive development occurs throughout childhood.",category:"형용사"},
  {word:"comprehensive",meaning:"포괄적인, 종합적인",example:"We need a comprehensive approach to the problem.",category:"형용사"},
  {word:"controversial",meaning:"논란이 많은",example:"The policy remains controversial.",category:"형용사"},
  {word:"conventional",meaning:"전통적인, 관습적인",example:"Conventional methods are no longer effective.",category:"형용사"},
  {word:"cumulative",meaning:"누적되는",example:"The cumulative effect of pollution is devastating.",category:"형용사"},
  {word:"demographic",meaning:"인구통계학의",example:"Demographic changes affect the economy.",category:"형용사"},
  {word:"empirical",meaning:"경험적인, 실증적인",example:"The claim lacks empirical evidence.",category:"형용사"},
  {word:"equitable",meaning:"공평한, 공정한",example:"We need a more equitable distribution of wealth.",category:"형용사"},
  {word:"erroneous",meaning:"잘못된, 틀린",example:"The report contained erroneous information.",category:"형용사"},
  {word:"ethical",meaning:"윤리적인",example:"This raises serious ethical questions.",category:"형용사"},
  {word:"explicit",meaning:"명시적인, 분명한",example:"The instructions were explicit.",category:"형용사"},
  {word:"formidable",meaning:"강력한, 만만찮은",example:"She faced a formidable challenge.",category:"형용사"},
  {word:"fundamental",meaning:"근본적인, 기본적인",example:"Education is a fundamental right.",category:"형용사"},
  {word:"hypothetical",meaning:"가설의, 가정의",example:"Consider a hypothetical scenario.",category:"형용사"},
  {word:"indigenous",meaning:"토착의, 원주민의",example:"Indigenous cultures should be preserved.",category:"형용사"},
  {word:"integral",meaning:"필수적인, 불가결한",example:"Technology is an integral part of modern life.",category:"형용사"},
  {word:"intrinsic",meaning:"본질적인, 고유한",example:"The intrinsic value of education goes beyond employment.",category:"형용사"},
  {word:"intuitive",meaning:"직관적인",example:"The interface is intuitive and easy to use.",category:"형용사"},
  {word:"mundane",meaning:"평범한, 일상적인",example:"Even mundane tasks can be made interesting.",category:"형용사"},
  {word:"negligible",meaning:"무시할 수 있는, 미미한",example:"The difference was negligible.",category:"형용사"},
  {word:"nominal",meaning:"명목상의, 이름뿐인",example:"He received only a nominal fee.",category:"형용사"},
  {word:"obsolete",meaning:"쓸모없는, 구식의",example:"The technology is already obsolete.",category:"형용사"},
  {word:"paradoxical",meaning:"역설적인, 모순된",example:"It seems paradoxical but it is true.",category:"형용사"},
  {word:"pervasive",meaning:"널리 퍼진, 만연한",example:"Social media has a pervasive influence.",category:"형용사"},
  {word:"pivotal",meaning:"중추적인, 핵심적인",example:"This was a pivotal moment in history.",category:"형용사"},
  {word:"pragmatic",meaning:"실용적인",example:"We need a pragmatic approach to the problem.",category:"형용사"},
  {word:"prominent",meaning:"두드러진, 유명한",example:"She is a prominent figure in politics.",category:"형용사"},
  {word:"provisional",meaning:"임시의, 잠정적인",example:"A provisional agreement was reached.",category:"형용사"},
  {word:"rudimentary",meaning:"기초적인, 초보적인",example:"He has only a rudimentary understanding.",category:"형용사"},
  {word:"salient",meaning:"두드러진, 현저한",example:"The salient features of the plan were discussed.",category:"형용사"},
  {word:"skeptical",meaning:"회의적인",example:"Scientists remain skeptical about the findings.",category:"형용사"},
  {word:"sparse",meaning:"드문, 희박한",example:"Vegetation is sparse in desert regions.",category:"형용사"},
  {word:"stagnant",meaning:"침체된, 정체된",example:"The economy has been stagnant for years.",category:"형용사"},
  {word:"stringent",meaning:"엄격한, 엄중한",example:"Stringent regulations were imposed.",category:"형용사"},
  {word:"subsequent",meaning:"그 다음의, 후속의",example:"Subsequent research confirmed the findings.",category:"형용사"},
  {word:"substantial",meaning:"상당한, 실질적인",example:"There has been a substantial improvement.",category:"형용사"},
  {word:"synthetic",meaning:"합성의, 인공의",example:"Synthetic materials replaced natural fibers.",category:"형용사"},
  {word:"tentative",meaning:"잠정적인, 확실하지 않은",example:"We reached a tentative agreement.",category:"형용사"},
  {word:"ubiquitous",meaning:"어디에나 있는, 편재하는",example:"Smartphones have become ubiquitous.",category:"형용사"},
  {word:"viable",meaning:"실행 가능한, 생존 가능한",example:"This is not a viable option.",category:"형용사"},
  {word:"volatile",meaning:"변덕스러운, 불안정한",example:"The stock market is highly volatile.",category:"형용사"},
  {word:"adverse",meaning:"불리한, 부정적인",example:"The drug has adverse side effects.",category:"형용사"},
  {word:"analogous",meaning:"유사한",example:"The situation is analogous to what happened before.",category:"형용사"},
  {word:"anonymous",meaning:"익명의",example:"The donation was made by an anonymous benefactor.",category:"형용사"},
  {word:"authentic",meaning:"진짜의, 진정한",example:"Is the painting authentic or a copy?",category:"형용사"},
  {word:"benign",meaning:"양성의, 해가 없는",example:"The tumor turned out to be benign.",category:"형용사"},
  {word:"coherent",meaning:"일관된, 논리적인",example:"He gave a coherent account of what happened.",category:"형용사"},
  {word:"concurrent",meaning:"동시에 일어나는",example:"The two events were concurrent.",category:"형용사"},
  {word:"conspicuous",meaning:"눈에 띄는, 뚜렷한",example:"His absence was conspicuous.",category:"형용사"},
  {word:"deficient",meaning:"부족한, 결핍된",example:"The diet is deficient in vitamins.",category:"형용사"},
  {word:"discreet",meaning:"신중한, 분별 있는",example:"He was discreet about the matter.",category:"형용사"},
  {word:"elusive",meaning:"파악하기 힘든, 포착하기 어려운",example:"Happiness can be elusive.",category:"형용사"},
  {word:"imminent",meaning:"임박한, 목전의",example:"A storm is imminent.",category:"형용사"},
  {word:"imperative",meaning:"필수적인, 긴급한",example:"It is imperative that we act now.",category:"형용사"},
  {word:"indispensable",meaning:"필수불가결한",example:"Water is indispensable for life.",category:"형용사"},
  {word:"inherent",meaning:"고유한, 내재된",example:"There are inherent dangers in the plan.",category:"형용사"},
  {word:"lucrative",meaning:"수익성 좋은",example:"Tourism is a lucrative industry.",category:"형용사"},
  {word:"meticulous",meaning:"꼼꼼한, 세심한",example:"She is meticulous in her research.",category:"형용사"},
  {word:"susceptible",meaning:"영향받기 쉬운, 취약한",example:"Young children are susceptible to infections.",category:"형용사"},
  {word:"underlying",meaning:"근본적인, 기저의",example:"The underlying cause of the problem is poverty.",category:"형용사"},
  {word:"alleged",meaning:"주장된, 혐의를 받는",example:"The alleged criminal was arrested.",category:"형용사"},
  {word:"affluent",meaning:"부유한",example:"They live in an affluent neighborhood.",category:"형용사"},

  // ══════════════════════════════════════
  // 부사 (30개)
  // ══════════════════════════════════════
  {word:"simultaneously",meaning:"동시에",example:"The events occurred simultaneously.",category:"부사"},
  {word:"merely",meaning:"단지, 그저",example:"He is merely stating the facts.",category:"부사"},
  {word:"predominantly",meaning:"주로, 대부분",example:"The audience was predominantly young.",category:"부사"},
  {word:"allegedly",meaning:"주장에 의하면",example:"He allegedly committed the crime at night.",category:"부사"},
  {word:"virtually",meaning:"사실상, 거의",example:"The task is virtually impossible.",category:"부사"},
  {word:"inherently",meaning:"본질적으로",example:"The system is inherently flawed.",category:"부사"},
  {word:"explicitly",meaning:"명시적으로",example:"The rules explicitly prohibit cheating.",category:"부사"},
  {word:"implicitly",meaning:"암묵적으로",example:"She implicitly agreed by not objecting.",category:"부사"},
  {word:"inevitably",meaning:"불가피하게",example:"Prices will inevitably rise.",category:"부사"},
  {word:"considerably",meaning:"상당히",example:"The results differ considerably.",category:"부사"},
  {word:"marginally",meaning:"약간, 근소하게",example:"Sales increased only marginally.",category:"부사"},
  {word:"profoundly",meaning:"깊이, 심오하게",example:"The experience profoundly changed him.",category:"부사"},
  {word:"exclusively",meaning:"독점적으로, 오로지",example:"The product is sold exclusively online.",category:"부사"},
  {word:"paradoxically",meaning:"역설적으로",example:"Paradoxically, more choice led to less happiness.",category:"부사"},
  {word:"disproportionately",meaning:"불균형하게",example:"The poor are disproportionately affected.",category:"부사"},
  {word:"arguably",meaning:"논쟁의 여지가 있지만, 거의 틀림없이",example:"She is arguably the best player.",category:"부사"},
  {word:"substantially",meaning:"상당히, 실질적으로",example:"Costs have increased substantially.",category:"부사"},
  {word:"fundamentally",meaning:"근본적으로",example:"The two approaches are fundamentally different.",category:"부사"},
  {word:"inadvertently",meaning:"실수로, 부주의하게",example:"He inadvertently deleted the file.",category:"부사"},
  {word:"intuitively",meaning:"직관적으로",example:"The answer seems intuitively correct.",category:"부사"},
  {word:"perpetually",meaning:"끊임없이, 영원히",example:"He is perpetually busy.",category:"부사"},
  {word:"predominantly",meaning:"주로, 압도적으로",example:"The area is predominantly rural.",category:"부사"},
  {word:"provisionally",meaning:"임시로, 잠정적으로",example:"The agreement was provisionally accepted.",category:"부사"},
  {word:"rigorously",meaning:"엄격하게, 철저하게",example:"The data was rigorously tested.",category:"부사"},
  {word:"systematically",meaning:"체계적으로",example:"The evidence was systematically collected.",category:"부사"},
  {word:"tentatively",meaning:"잠정적으로, 조심스럽게",example:"The meeting is tentatively scheduled for Friday.",category:"부사"},
  {word:"unanimously",meaning:"만장일치로",example:"The decision was unanimously approved.",category:"부사"},
  {word:"voluntarily",meaning:"자발적으로",example:"He voluntarily resigned from his position.",category:"부사"},
  {word:"intermittently",meaning:"간헐적으로",example:"Rain fell intermittently throughout the day.",category:"부사"},
  {word:"retrospectively",meaning:"회고적으로, 소급하여",example:"Retrospectively, the decision was a mistake.",category:"부사"},

  // ══════════════════════════════════════
  // 연결어/논리어 (20개)
  // ══════════════════════════════════════
  {word:"nevertheless",meaning:"그럼에도 불구하고",example:"It was raining; nevertheless, they went hiking.",category:"연결어"},
  {word:"conversely",meaning:"반대로",example:"Rich countries consume more; conversely, poor countries save more.",category:"연결어"},
  {word:"accordingly",meaning:"따라서, 그에 맞게",example:"The results were clear, and we acted accordingly.",category:"연결어"},
  {word:"thereby",meaning:"그것에 의하여",example:"He studied hard, thereby improving his grades.",category:"연결어"},
  {word:"notwithstanding",meaning:"~에도 불구하고",example:"Notwithstanding the difficulties, they succeeded.",category:"연결어"},
  {word:"furthermore",meaning:"게다가, 더욱이",example:"The plan is costly; furthermore, it is impractical.",category:"연결어"},
  {word:"moreover",meaning:"게다가, 더구나",example:"The project is behind schedule; moreover, it is over budget.",category:"연결어"},
  {word:"consequently",meaning:"결과적으로, 따라서",example:"He missed the deadline; consequently, he lost the contract.",category:"연결어"},
  {word:"nonetheless",meaning:"그럼에도 불구하고",example:"The task was difficult; nonetheless, she completed it.",category:"연결어"},
  {word:"alternatively",meaning:"그 대신에, 혹은",example:"You could fly; alternatively, you could take the train.",category:"연결어"},
  {word:"likewise",meaning:"마찬가지로",example:"He is talented; likewise, his sister excels in music.",category:"연결어"},
  {word:"hence",meaning:"따라서, 그러므로",example:"The evidence is clear; hence, no further debate is needed.",category:"연결어"},
  {word:"whereby",meaning:"그것에 의하여, ~하는 바의",example:"They introduced a system whereby all could participate.",category:"연결어"},
  {word:"insofar",meaning:"~하는 한에 있어서",example:"Insofar as I know, the plan is still on track.",category:"연결어"},
  {word:"inasmuch",meaning:"~이기 때문에, ~인 한",example:"He is qualified inasmuch as he has the right experience.",category:"연결어"},
  {word:"irrespective",meaning:"~에 상관없이",example:"All students are welcome, irrespective of background.",category:"연결어"},
  {word:"in contrast",meaning:"대조적으로",example:"In contrast, the second group showed no improvement.",category:"연결어"},
  {word:"in turn",meaning:"결국, 차례로",example:"Pollution affects health, which in turn raises costs.",category:"연결어"},
  {word:"that is",meaning:"즉, 다시 말해서",example:"He is bilingual — that is, he speaks two languages.",category:"연결어"},
  {word:"on the contrary",meaning:"이와 반대로",example:"It is not simple; on the contrary, it is quite complex.",category:"연결어"},

  // ══════════════════════════════════════
  // 혼동어/수능 함정 어휘 (100개)
  // ══════════════════════════════════════
  {word:"adverse",meaning:"불리한, 역효과의",example:"The drug had adverse effects on patients.",category:"혼동어"},
  {word:"averse",meaning:"싫어하는, 반대하는",example:"She is averse to taking unnecessary risks.",category:"혼동어"},
  {word:"affect",meaning:"영향을 미치다 (동사)",example:"The weather affects our mood.",category:"혼동어"},
  {word:"effect",meaning:"결과, 효과 (명사) / 초래하다 (동사)",example:"The new policy had a positive effect.",category:"혼동어"},
  {word:"complement",meaning:"보완하다/보완물",example:"The wine complements the meal perfectly.",category:"혼동어"},
  {word:"compliment",meaning:"칭찬하다/칭찬",example:"She complimented him on his presentation.",category:"혼동어"},
  {word:"principal",meaning:"주요한, 교장",example:"The principal reason is cost.",category:"혼동어"},
  {word:"principle",meaning:"원리, 원칙",example:"This goes against basic principles of fairness.",category:"혼동어"},
  {word:"precede",meaning:"선행하다, 앞서다",example:"Thunder is preceded by lightning.",category:"혼동어"},
  {word:"proceed",meaning:"진행하다, 나아가다",example:"Please proceed to the next item.",category:"혼동어"},
  {word:"elicit",meaning:"이끌어내다",example:"The speech elicited a strong reaction.",category:"혼동어"},
  {word:"illicit",meaning:"불법의",example:"Illicit trade in wildlife is increasing.",category:"혼동어"},
  {word:"emigrate",meaning:"(다른 나라로) 이주하다",example:"They emigrated from Korea to Canada.",category:"혼동어"},
  {word:"immigrate",meaning:"(다른 나라에서) 이민 오다",example:"Many people immigrated to the United States.",category:"혼동어"},
  {word:"perspective",meaning:"관점, 시각",example:"It depends on your perspective.",category:"혼동어"},
  {word:"prospective",meaning:"장래의, 예상되는",example:"Prospective students attended the open day.",category:"혼동어"},
  {word:"empathy",meaning:"공감, 감정이입",example:"Show empathy for others.",category:"혼동어"},
  {word:"apathy",meaning:"무관심, 냉담",example:"Voter apathy is a serious concern.",category:"혼동어"},
  {word:"adapt",meaning:"적응하다, 각색하다",example:"Animals adapt to their environment.",category:"혼동어"},
  {word:"adopt",meaning:"채택하다, 입양하다",example:"The company adopted a new strategy.",category:"혼동어"},
  {word:"ingenious",meaning:"독창적인, 기발한",example:"She devised an ingenious solution.",category:"혼동어"},
  {word:"ingenuous",meaning:"순진한, 솔직한",example:"His ingenuous smile charmed everyone.",category:"혼동어"},
  {word:"disinterested",meaning:"공정한, 사심 없는",example:"We need a disinterested judge.",category:"혼동어"},
  {word:"uninterested",meaning:"관심 없는, 무관심한",example:"He seemed uninterested in the lecture.",category:"혼동어"},
  {word:"sensible",meaning:"분별 있는, 합리적인",example:"That is a sensible decision.",category:"혼동어"},
  {word:"sensitive",meaning:"민감한, 섬세한",example:"She is sensitive to criticism.",category:"혼동어"},
  {word:"economic",meaning:"경제의, 경제학의",example:"The economic outlook is positive.",category:"혼동어"},
  {word:"economical",meaning:"경제적인, 절약하는",example:"The car is very economical to run.",category:"혼동어"},
  {word:"continual",meaning:"반복적인, 빈번한",example:"The continual interruptions were annoying.",category:"혼동어"},
  {word:"continuous",meaning:"끊임없는, 연속적인",example:"The factory runs on a continuous cycle.",category:"혼동어"},
  {word:"assure",meaning:"확신시키다 (사람에게)",example:"I assure you that it is safe.",category:"혼동어"},
  {word:"ensure",meaning:"확실히 하다, 보장하다",example:"Steps were taken to ensure safety.",category:"혼동어"},
  {word:"insure",meaning:"보험에 들다",example:"You should insure your property.",category:"혼동어"},
  {word:"deduce",meaning:"추론하다 (논리적으로)",example:"We can deduce the answer from the evidence.",category:"혼동어"},
  {word:"induce",meaning:"유발하다, 유도하다",example:"The drug can induce drowsiness.",category:"혼동어"},
  {word:"reduce",meaning:"줄이다, 감소시키다",example:"We need to reduce carbon emissions.",category:"혼동어"},
  {word:"preserve",meaning:"보존하다, 유지하다",example:"We must preserve the rainforest.",category:"혼동어"},
  {word:"conserve",meaning:"아끼다, 절약하다",example:"We need to conserve water during the drought.",category:"혼동어"},
  {word:"reserve",meaning:"예약하다, 보유하다",example:"I reserved a table at the restaurant.",category:"혼동어"},
  {word:"respectable",meaning:"존경할 만한, 상당한",example:"He earned a respectable salary.",category:"혼동어"},
  {word:"respective",meaning:"각각의",example:"They returned to their respective homes.",category:"혼동어"},
  {word:"literal",meaning:"문자 그대로의",example:"The literal meaning is quite different.",category:"혼동어"},
  {word:"literary",meaning:"문학의, 문학적인",example:"She has a deep literary knowledge.",category:"혼동어"},
  {word:"literate",meaning:"글을 읽고 쓸 줄 아는",example:"All children should be literate by age 8.",category:"혼동어"},
  {word:"comparable",meaning:"비교할 만한, 유사한",example:"The two products are comparable in quality.",category:"혼동어"},
  {word:"comparative",meaning:"비교의, 상대적인",example:"This is a comparative study of two cultures.",category:"혼동어"},
  {word:"credible",meaning:"믿을 수 있는, 신뢰할 수 있는",example:"Is the witness credible?",category:"혼동어"},
  {word:"creditable",meaning:"칭찬할 만한",example:"The team put in a creditable performance.",category:"혼동어"},
  {word:"negligent",meaning:"태만한, 부주의한",example:"The doctor was found negligent.",category:"혼동어"},
  {word:"negligible",meaning:"무시해도 될 정도의",example:"The cost difference is negligible.",category:"혼동어"},
  {word:"contemptuous",meaning:"경멸하는",example:"He was contemptuous of their efforts.",category:"혼동어"},
  {word:"contemptible",meaning:"경멸받을 만한",example:"His behavior was contemptible.",category:"혼동어"},
  {word:"historic",meaning:"역사적으로 중요한",example:"It was a historic moment for the country.",category:"혼동어"},
  {word:"historical",meaning:"역사의, 역사에 관한",example:"The novel is based on historical events.",category:"혼동어"},
  {word:"judicial",meaning:"사법의, 재판의",example:"The judicial system needs reform.",category:"혼동어"},
  {word:"judicious",meaning:"현명한, 사려 깊은",example:"She made a judicious decision.",category:"혼동어"},
  {word:"comprehensive",meaning:"포괄적인",example:"A comprehensive review was conducted.",category:"혼동어"},
  {word:"comprehensible",meaning:"이해할 수 있는",example:"The explanation was clear and comprehensible.",category:"혼동어"},
  {word:"industrial",meaning:"산업의",example:"Industrial growth slowed down.",category:"혼동어"},
  {word:"industrious",meaning:"근면한",example:"She is an industrious worker.",category:"혼동어"},
  {word:"personal",meaning:"개인적인",example:"This is a personal matter.",category:"혼동어"},
  {word:"personnel",meaning:"인원, 직원",example:"All personnel must attend the meeting.",category:"혼동어"},
  {word:"momentous",meaning:"중대한",example:"It was a momentous occasion.",category:"혼동어"},
  {word:"momentary",meaning:"순간적인",example:"There was a momentary silence.",category:"혼동어"},
  {word:"considerable",meaning:"상당한",example:"She has considerable experience.",category:"혼동어"},
  {word:"considerate",meaning:"사려 깊은, 배려하는",example:"He is always considerate of others.",category:"혼동어"},
  {word:"imaginable",meaning:"상상할 수 있는",example:"They tried every method imaginable.",category:"혼동어"},
  {word:"imaginary",meaning:"상상의, 가상의",example:"The story takes place in an imaginary world.",category:"혼동어"},
  {word:"imaginative",meaning:"상상력이 풍부한",example:"She is a highly imaginative writer.",category:"혼동어"},
  {word:"sociable",meaning:"사교적인",example:"He is a sociable and friendly person.",category:"혼동어"},
  {word:"social",meaning:"사회적인",example:"Social inequality is a major issue.",category:"혼동어"},
  {word:"proscribe",meaning:"금지하다",example:"The law proscribes such behavior.",category:"혼동어"},
  {word:"prescribe",meaning:"처방하다, 규정하다",example:"The doctor prescribed medication.",category:"혼동어"},
  {word:"collaborate",meaning:"협력하다",example:"The two teams collaborated on the project.",category:"혼동어"},
  {word:"corroborate",meaning:"확증하다, 뒷받침하다",example:"The evidence corroborated her testimony.",category:"혼동어"},
  {word:"stationary",meaning:"정지된, 움직이지 않는",example:"The car was stationary at the traffic light.",category:"혼동어"},
  {word:"stationery",meaning:"문구류",example:"She bought some stationery for school.",category:"혼동어"},
  {word:"censor",meaning:"검열하다",example:"The government censored the media.",category:"혼동어"},
  {word:"censure",meaning:"비난하다, 문책하다",example:"He was censured for his conduct.",category:"혼동어"},
  {word:"defer",meaning:"미루다, 따르다",example:"I defer to your expertise on this matter.",category:"혼동어"},
  {word:"differ",meaning:"다르다, 의견이 다르다",example:"Opinions differ on this issue.",category:"혼동어"},
  {word:"imminent",meaning:"임박한",example:"Danger is imminent.",category:"혼동어"},
  {word:"eminent",meaning:"저명한, 탁월한",example:"She is an eminent scholar.",category:"혼동어"},
  {word:"immanent",meaning:"내재하는",example:"The divine is immanent in all things.",category:"혼동어"},
  {word:"allude",meaning:"암시하다, 언급하다",example:"She alluded to the recent scandal.",category:"혼동어"},
  {word:"elude",meaning:"피하다, 벗어나다",example:"The answer eluded me for days.",category:"혼동어"},
  {word:"amoral",meaning:"도덕관념이 없는",example:"Animals are amoral beings.",category:"혼동어"},
  {word:"immoral",meaning:"부도덕한",example:"His actions were immoral.",category:"혼동어"},
  {word:"discreet",meaning:"신중한, 눈에 띄지 않는",example:"Please be discreet about this matter.",category:"혼동어"},
  {word:"discrete",meaning:"별개의, 분리된",example:"The project has three discrete phases.",category:"혼동어"},
  {word:"flounder",meaning:"허둥대다, 허우적거리다",example:"The company floundered during the recession.",category:"혼동어"},
  {word:"founder",meaning:"침몰하다, 실패하다 / 창립자",example:"The ship foundered in the storm.",category:"혼동어"},
  {word:"luxurious",meaning:"호화로운",example:"They stayed in a luxurious hotel.",category:"혼동어"},
  {word:"luxuriant",meaning:"무성한, 풍부한",example:"The garden had luxuriant vegetation.",category:"혼동어"},
  {word:"mitigate",meaning:"완화하다",example:"Measures to mitigate climate change.",category:"혼동어"},
  {word:"militate",meaning:"작용하다 (against와 함께 불리하게)",example:"Several factors militated against success.",category:"혼동어"},
  {word:"tortuous",meaning:"구불구불한, 복잡한",example:"The road was tortuous and narrow.",category:"혼동어"},
  {word:"torturous",meaning:"고문하는 듯한, 괴로운",example:"The wait was torturous.",category:"혼동어"},
];

// 오늘 학습할 단어 20개 선택
function getTodayWords() {
  const today = new Date().toISOString().slice(0, 10);
  const saved = localStorage.getItem('vocabToday');
  const savedDate = localStorage.getItem('vocabTodayDate');

  if (saved && savedDate === today) {
    return JSON.parse(saved);
  }

  // 새 날짜 → 새 단어 선택
  const shuffled = [...VOCAB_DB].sort(() => Math.random() - 0.5);
  const words = shuffled.slice(0, 20);
  localStorage.setItem('vocabToday', JSON.stringify(words));
  localStorage.setItem('vocabTodayDate', today);
  return words;
}

// 학습 진행 상태
function getVocabProgress() {
  return JSON.parse(localStorage.getItem('vocabProgress') || '{"learned":[],"mastered":[]}');
}

function saveVocabProgress(progress) {
  localStorage.setItem('vocabProgress', JSON.stringify(progress));
}
